version: '3'
services:

  mongodb:
    container_name: waproject-ebay-mongo
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./.docker-data/mongodb:/data/db
  
  rabbitmq:
    container_name: waproject-ebay-rabbit
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    volumes: 
      - ./.docker-data/rabbitmq:/var/lib/rabbitmq
    container_name: rabbitmq
    ports:
     - 15672:15672
     - 5672:5672